import type { Metadata } from "next";

import Header from "@/components/common/header/header";
import Footer from "@/components/common/footer/footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "WTS Web Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header />
        {children}
        <Footer />
        <div id="message-box"></div>
      </body>
    </html>
  );
}
