import type { Metadata } from "next";

import Header from "@/components/common/header/header";
import Footer from "@/components/common/footer/footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "WTS Web Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  projects,
}: Readonly<{
  children: React.ReactNode;
  projects: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="main">
          <section>{children}</section>
          <section>{projects}</section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
