import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "WTS Web Editor - Test Page",
  description: "Generated by create next app",
};

export default function TestLayout({
  children,
  notification,
}: Readonly<{
  children: React.ReactNode;
  notification: React.ReactNode;
}>) {
  return (
    <div className="py-8">
      {children}
      {notification}
    </div>
  );
}
